name: Lint Detect and Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-detect-and-fix:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.15

      - name: Install Python dependencies
        run: pip install black autopep8 oitnb

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
          autopep8: true
          autopop8_auto_fix: true
          oitnb: true
          oitnb_auto_fix: true
